### ISSUE TITLE
custom dataset

### ISSUE THREAD

**Issue by lhfabc9** [adhirajghosh/RPTM_reid#2]
Hello, is it possible to train a custom dataset? How to do it if possible?

**Comment by adhirajghosh** [comment]
In principle, it is possible to train a custom dataset. You would need to maintain the naming convention and file location structure of one of the datasets I have used to use the same dataset file in /datasets/. Feel free to reach out if you have questions here.

Regarding the gms and index files, I will make the scripts public soon. They are based on [GMS](https://github.com/JiawangBian/GMS-Feature-Matcher). Stay tuned.

**Comment by RicoSuaveGuapo** [comment]
Hi~ Thanks for the interesting work. I am also curious about how the gms and index files are made. Is there any update on this?
