### ISSUE TITLE
AttributeError: TEST_SIZE

### ISSUE THREAD

**Issue by QiuZuowei** [adhirajghosh/RPTM_reid#4]
Hi, thanks for your great work. I trained the model on the Veri dataset and encountered an error when executing `python main.py --config_file configs/veri_r101.yml` in the terminal, as shown in the following figure.
感谢您的工作，我在veri数据集上训练模型的时候，在终端中执行python main.py --config_file configs/veri_r101.yml，程序报错，如下图所示。
![1690102584361](https://github.com/adhirajghosh/RPTM_reid/assets/101374919/2dfe9249-4f20-4808-b326-d83558eced8c)

I checked [veri_ r101.yml](https://github.com/adhirajghosh/RPTM_reid/blob/main/configs/veri_r101.yml) file, found no **_TEST.TEST_SIZE_** parameter, which is needed in [kwargs.py](https://github.com/adhirajghosh/RPTM_reid/blob/main/utils/kwargs.py), line 27.
我查看了[veri_r101.yml](https://github.com/adhirajghosh/RPTM_reid/blob/main/configs/veri_r101.yml)文件，发现没有**_TEST.TEST_SIZE_**这个参数。
![image](https://github.com/adhirajghosh/RPTM_reid/assets/101374919/6b4db3ac-bbfb-4498-afd6-91858100a326)
![1690103552907](https://github.com/adhirajghosh/RPTM_reid/assets/101374919/b8b0900f-3efe-45c0-84e2-25dd55cb87a3)

How should I solve this problem? Looking forward to your reply!
我应该怎样解决这个问题呢？期待您的回复！

**Comment by Abithan07** [comment]
Hi! I encountered the same issue and was able to resolve it by updating the defaults.py file in the config folder.

To fix it, add the following line in the "# Test options" section of defaults.py:

_C.TEST.TEST_SIZE = 11579  # Add this line to set a default value for TEST_SIZE
