### ISSUE TITLE
About mAP and weigts

### ISSUE THREAD

**Issue by moonstarL** [adhirajghosh/RPTM_reid#6]
Hello, thank you for your contribution. 
The accuracy of rank1 in our training results is consistent with that described in the paper, but the mAP is quite different from the one described in the paper.
Can you please open source your training weights?

**Comment by adhirajghosh** [comment]
This matter should be resolved by using re-ranking which we have implemented in our work, unless you are using the VehicleID dataset. 
I hope this helps.

**Comment by lzyuan168** [comment]
@adhirajghosh Hi may I request for your trained weights for inference purposes? Thank you
